### PR TITLE
[Do Not Merge] Feature - wallet & build basics

### PR DESCRIPTION
**Pull request by ch4ot1c**
### Working towards a successful build without `-disablewallet`.

- Logging modernized (`BCLog::ZRPC`, `ZRPCUNSAFE`) 
- Prefer STL (`std::`) over Boost
- Prefer `uint64_t` over `size_t`
- Add remaining z methods to wallet.h
- Add `pzcashparams`
- Replace `CBitcoinAddress` with `CTxDestination`

- `strMessageMagic` set to `BitcoinPrivate Signed Message:\n`

Remaining -
- `Sighash` signature from old codebase needs to must match
- Remove / detach any Zcash related upgrade code

Edit: Changes from this PR have been significantly revised, but are still being used for reference; see other pull requests.

### CODE REVIEW

**Comment by ch4ot1c** [comment]
Now builds successfully on Ubuntu 16.10!

Note - attempting to build on Ubuntu 16.04 instead of Ubuntu 16.10 will fail with:
```
snark/libsnark.a(profiling.o): In function `libsnark::enter_block(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)':
profiling.cpp:(.text+0x14e7): undefined reference to `GOMP_critical_start'
profiling.cpp:(.text+0x1558): undefined reference to `GOMP_critical_end'
snark/libsnark.a(profiling.o): In function `libsnark::leave_block(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)':
profiling.cpp:(.text+0x1cc5): undefined reference to `GOMP_critical_start'
profiling.cpp:(.text+0x1ed6): undefined reference to `GOMP_critical_end'
collect2: error: ld returned 1 exit status
```
`sudo apt-get dist-upgrade` to fix.

Note - MacOS build fails due to `unsupported option -fopenmp`.

File: src/asyncrpcoperation.cpp [hunk 1]
```diff
@@ -27,15 +27,19 @@ std::map<OperationStatus, std::string> OperationStatusMap = {
 /**
  * Every operation instance should have a globally unique id
  */
-AsyncRPCOperation::AsyncRPCOperation() : error_code_(0), error_message_() {
+AsyncRPCOperation::AsyncRPCOperation(CWallet* const wallet) :
```
Comment (jc23424) [inline src/asyncrpcoperation.cpp]: what is the ownership model for wallets?
i think you'll want to hang onto a shared pointer here so that the wallet sticks around until you're done if someone happens to call `RemoveWallet` in the interim

**Comment by ch4ot1c** [comment]
Closing in favor of #28
